### ISSUE TITLE
How to catch errors?

### ISSUE THREAD

**Issue by doits** [adhearsion/blather#148] opened 2015-07-14 17:42 UTC
I'm trying to catch errors from blather. I'm totally new to event machine and thread programming in ruby, so maybe this looks silly, but ...

I've created a blather client successfully like this:

``` ruby
# client.rb

require 'eventmachine' 
require 'blather/client/dsl'

class Client
  include Blather::DSL

  def initialize
    setup 'jabber@id/name', 'password'
  end

  def connect
    Thread.new do
      EM.run { client.connect }
    end
  end

  def connected?
    client.connected?
  end
end

client = Client.new
client.connect

until client.connected?
  puts 'Waiting for connection ...'
  sleep 1
end

client.say 'some@jid', 'hello!'
sleep 1000
```

This works good so far.

I can now trigger the error `Stream Error (conflict): Replaced by new connection` by simply running this script twice:

```
ruby client.rb & ruby client.rb
```

This error is OK of course, but how can I catch it so I can handle it in a custom way? I tried to rescue it everywhere without success, so it looks like this now:

``` ruby
  def connect
    begin
      Thread.new do
        begin
          EM.error_handler { puts 'rescued?' }
          EM.run do
            begin
              client.connect
            rescue
              puts 'rescued?'
            end
          end
        rescue
          puts 'rescued?'
        end
      end
    rescue
      puts 'rescued?'
    end
  end
```

But the error is never catched, even with this connect monstrosity above. What am I missing?

**Comment by benlangfeld** [comment] 2015-07-14 20:15
Thanks for asking. I'm going to close this as a duplicate of https://github.com/adhearsion/blather/issues/73.

**Closed by benlangfeld** 2015-07-14 20:15 UTC

**Comment by doits** [comment] 2015-07-15 08:32
I'm not sure if this is exactly the same, because overwriting `unbind` as in #73 didn't work for me, but I managed to register a custom error handler which at least gets called additionally like this:

``` ruby
class Blather::Client
  attr_accessor :custom_error_handler

  alias_method :setup_initial_handlers_orig, :setup_initial_handlers
  def setup_initial_handlers
    register_handler :error do |err|
      custom_error_handler.call(err) if custom_error_handler
    end

    setup_initial_handlers_orig
  end
end

class Client
  include Blather::DSL

  def initialize
    client.custom_error_handler = proc do |err|
      # will get called on error like StreamError
    end
  end
end
```
